version: "3.7"
name: lms
services:
  mariadb:
    image: mariadb:10.8
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: frappe
    volumes:
      - mariadb-data:/var/lib/mysql

  redis-cache:
    image: redis:alpine
    volumes:
      - redis-cache-data:/data

  redis-queue:
    image: redis:alpine
    volumes:
      - redis-queue-data:/data

  frappe:
    image: frappe/bench:latest
    command: bash /workspace/init.sh
    environment:
      - SHELL=/bin/bash
      - FRAPPE_SITE_NAME=${FRAPPE_SITE_NAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - NODE_VERSION_DEVELOP=18.16.0
    working_dir: /home/frappe
    volumes:
      - .:/workspace
      - frappe-sites:/home/frappe/frappe-bench/sites
      - frappe-logs:/home/frappe/frappe-bench/logs
    ports:
      - 80:8000
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue

volumes:
  mariadb-data:
  redis-cache-data:
  redis-queue-data:
  frappe-sites:
  frappe-logs:
