version: "3.7"
name: lms
services:
  mariadb:
    image: mariadb:10.8
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=frappe
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - frappe_network

  redis-cache:
    image: redis:alpine
    volumes:
      - redis-cache-data:/data
    networks:
      - frappe_network

  redis-queue:
    image: redis:alpine
    volumes:
      - redis-queue-data:/data
    networks:
      - frappe_network

  frappe:
    image: frappe/bench:latest
    command: bash /docker/init.sh  # Correct path to the init.sh file
    environment:
      - SHELL=/bin/bash
      - FRAPPE_SITE_NAME=lms.goats.fr
      - MYSQL_ROOT_PASSWORD=123
      - ADMIN_PASSWORD=admin123
      - NODE_VERSION_DEVELOP=18.16.0
    working_dir: /home/frappe
    volumes:
      - ./docker:/docker  # Correctly bind the `docker` folder
      - frappe-sites:/home/frappe/frappe-bench/sites
      - frappe-logs:/home/frappe/frappe-bench/logs
    ports:
      - 90:8000  # Expose port 8000 on port 90 of the host
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
    networks:
      - frappe_network

volumes:
  mariadb-data:
  redis-cache-data:
  redis-queue-data:
  frappe-sites:
  frappe-logs:

networks:
  frappe_network:
    driver: bridge
