version: "3.7"
name: lms
services:
  mariadb:
    image: mariadb:10.8
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=frappe
    volumes:
      - mariadb-data:/var/lib/mysql

  redis-cache:
    image: redis:alpine
    volumes:
      - redis-cache-data:/data

  redis-queue:
    image: redis:alpine
    volumes:
      - redis-queue-data:/data

  frappe:
    image: frappe/bench:latest
    command: bash /scripts/init.sh
    environment:
      - SHELL=/bin/bash
      - FRAPPE_SITE_NAME=lms.goats.fr
      - MYSQL_ROOT_PASSWORD=123
      - ADMIN_PASSWORD=admin123
      - NODE_VERSION_DEVELOP=18.16.0
    working_dir: /home/frappe
    volumes:
      - type: bind
        source: ./docker
        target: /scripts
      - frappe-sites:/home/frappe/frappe-bench/sites
      - frappe-logs:/home/frappe/frappe-bench/logs
    ports:
      - 90:8000
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue

volumes:
  mariadb-data:
  redis-cache-data:
  redis-queue-data:
  frappe-sites:
  frappe-logs:
